Allow SlackClient rtm_connect exceptions to be raised
The SlackClient method rtm_connect does not provide a reason for
failed connections and only returns True or False. This change
makes it so:
    - Exceptions can be raised in the client's rtm_connect method
    - A connection can be established on instantiation

For example, this exception can now be raised so the problem is not
masked:
    urllib2.HTTPError: HTTP Error 429: Too Many Requests

The slack client can now be instantiated in this manner:
    sc = SlackClient(SLACK_TOKEN, connect=True)

Exceptions can also be raised by invoking rtm_connect as such:
    sc.rtm_connect(debug=True)